# Generated by Django 5.2.3 on 2025-07-05 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Quantidade de jogos')),
            ],
            options={
                'verbose_name': 'Interesse de jogo',
                'verbose_name_plural': 'Interesses de jogo',
                'ordering': ['sorteio__ano', 'sorteio__mes', 'jogador'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora')),
                ('duracao', models.DurationField(blank=True, null=True, verbose_name='Duração')),
                ('status', models.CharField(choices=[('S', 'Sorteado'), ('M', 'Marcado'), ('R', 'Realizado'), ('N', 'Não-realizado')], default='S', max_length=1, verbose_name='Status')),
                ('status_order', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['status_order', 'sorteio__ano', 'sorteio__mes', 'data'],
            },
        ),
        migrations.CreateModel(
            name='Placar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set1jogador1', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Set 1 Jogador 1')),
                ('set1jogador2', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Set 1 Jogador 2')),
                ('set2jogador1', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Set 2 Jogador 1')),
                ('set2jogador2', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Set 2 Jogador 2')),
                ('tiebreak1jogador1', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tie Break 1 Jogador 1')),
                ('tiebreak1jogador2', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tie Break 1 Jogador 2')),
                ('tiebreak2jogador1', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tie Break 2 Jogador 1')),
                ('tiebreak2jogador2', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tie Break 2 Jogador 2')),
                ('supertiejogador1', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Supertie Jogador 1')),
                ('supertiejogador2', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Supertie Jogador 2')),
            ],
            options={
                'verbose_name': 'Placar',
                'verbose_name_plural': 'Placares',
            },
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês')),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano')),
                ('data_inicio_interesses', models.DateField(verbose_name='Data de abertura da indicação de jogos')),
                ('status', models.CharField(choices=[('I', 'Indicação'), ('S', 'Sorteado')], default='I', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Sorteio',
                'verbose_name_plural': 'Sorteios',
                'ordering': ['-ano', '-mes'],
            },
        ),
    ]
