# Generated by Django 5.2.3 on 2025-07-04 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interessejogo',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='interesses_jogo', to=settings.AUTH_USER_MODEL, verbose_name='Jogador'),
        ),
        migrations.AddField(
            model_name='partida',
            name='jogador1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas_j1', to=settings.AUTH_USER_MODEL, verbose_name='Jogador 1'),
        ),
        migrations.AddField(
            model_name='partida',
            name='jogador2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas_j2', to=settings.AUTH_USER_MODEL, verbose_name='Jogador 2'),
        ),
        migrations.AddField(
            model_name='partida',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='partidas', to='Jogo.local', verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='partida',
            name='placar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='partida', to='Jogo.placar', verbose_name='Placar'),
        ),
        migrations.AddField(
            model_name='partida',
            name='sorteio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='partidas', to='Jogo.sorteio', verbose_name='Sorteio'),
        ),
        migrations.AddField(
            model_name='interessejogo',
            name='sorteio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='interesses_jogo', to='Jogo.sorteio', verbose_name='Sorteio'),
        ),
    ]
