# Generated by Django 5.2.3 on 2025-06-30 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jogo', '0001_initial'),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interessejogo',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='interesses_jogo', to='Usuario.usuario', verbose_name='Jogador'),
        ),
        migrations.AddField(
            model_name='partida',
            name='jogador1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas_j1', to='Usuario.usuario', verbose_name='Jogador 1'),
        ),
        migrations.AddField(
            model_name='partida',
            name='jogador2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas_j2', to='Usuario.usuario', verbose_name='Jogador 2'),
        ),
        migrations.AddField(
            model_name='partida',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='partidas', to='Jogo.local', verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='partida',
            name='placar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='partida', to='Jogo.placar', verbose_name='Placar'),
        ),
    ]
