# Generated by Django 5.2.3 on 2025-06-30 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jogo', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês')),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano')),
                ('data_inicio_interesses', models.DateField(verbose_name='Data de abertura da indicação de jogos')),
                ('status', models.CharField(choices=[('I', 'Indicação'), ('S', 'Sorteado')], default='I', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Sorteio',
                'verbose_name_plural': 'Sorteios',
                'ordering': ['ano', 'mes'],
            },
        ),
    ]
