# Generated by Django 5.2.3 on 2025-06-30 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jogo', '0003_sorteio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interessejogo',
            options={'ordering': ['sorteio__ano', 'sorteio__mes', 'jogador'], 'verbose_name': 'Interesse de jogo', 'verbose_name_plural': 'Interesses de jogo'},
        ),
        migrations.RemoveField(
            model_name='interessejogo',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='interessejogo',
            name='mes',
        ),
        migrations.AddField(
            model_name='interessejogo',
            name='sorteio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='interesses_jogo', to='Jogo.sorteio', verbose_name='Sorteio'),
        ),
    ]
