# Generated by Django 5.2.3 on 2025-07-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jogo', '0004_alter_interessejogo_options_remove_interessejogo_ano_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partida',
            options={'ordering': ['sorteio__ano', 'sorteio__mes', 'data'], 'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.RemoveField(
            model_name='partida',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='mes',
        ),
        migrations.AddField(
            model_name='partida',
            name='sorteio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='partidas', to='Jogo.sorteio', verbose_name='Sorteio'),
        ),
    ]
