# Generated by Django 5.2.3 on 2025-07-01 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jogo', '0005_alter_partida_options_remove_partida_ano_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorteio',
            options={'ordering': ['-ano', '-mes'], 'verbose_name': 'Sorteio', 'verbose_name_plural': 'Sorteios'},
        ),
        migrations.AddField(
            model_name='interessejogo',
            name='quantidade',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Quantidade de jogos'),
        ),
    ]
