# Generated by Django 5.2.3 on 2025-07-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jogo', '0006_alter_sorteio_options_interessejogo_quantidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partida',
            options={'ordering': ['status', 'sorteio__ano', 'sorteio__mes', 'data'], 'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.AddField(
            model_name='partida',
            name='status_order',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
