# Generated by Django 5.2.3 on 2025-07-02 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jogo', '0007_alter_partida_options_partida_status_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partida',
            options={'ordering': ['status_order', 'sorteio__ano', 'sorteio__mes', 'data'], 'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.AlterField(
            model_name='placar',
            name='set1jogador2',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Set 1 Jogador 2'),
        ),
        migrations.AlterField(
            model_name='placar',
            name='tiebreak1jogador1',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tie Break 1 Jogador 1'),
        ),
        migrations.AlterField(
            model_name='placar',
            name='tiebreak1jogador2',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tie Break 1 Jogador 2'),
        ),
        migrations.AlterField(
            model_name='placar',
            name='tiebreak2jogador1',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tie Break 2 Jogador 1'),
        ),
        migrations.AlterField(
            model_name='placar',
            name='tiebreak2jogador2',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tie Break 2 Jogador 2'),
        ),
    ]
